torchvision 0.13.1
AnacondaRecipes/torchvision-feedstock pull request #7
Opened 2022-11-29 14:57 UTC by skupr-anaconda

Update dependencies and tests

2022-11-29 14:59 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_996x6caoj1/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_996x6caoj1/clone/recipe/meta.yaml:119: missing_description: The recipe is missing a description
WARNING: /tmp/abs_996x6caoj1/clone/recipe/meta.yaml:119: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-29 15:28 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_7402b7_od_/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_7402b7_od_/clone/recipe/meta.yaml:119: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_7402b7_od_/clone/recipe/meta.yaml:119: missing_description: The recipe is missing a description
Warnings were found

</details>

2022-12-02 12:47 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_fadoe1aan4/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_fadoe1aan4/clone/recipe/meta.yaml:118: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_fadoe1aan4/clone/recipe/meta.yaml:118: missing_description: The recipe is missing a description
Warnings were found

</details>

2022-12-02 13:25 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_c19111mec5/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_c19111mec5/clone/recipe/meta.yaml:118: missing_description: The recipe is missing a description
WARNING: /tmp/abs_c19111mec5/clone/recipe/meta.yaml:118: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-02 13:48 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_3ahasv28u2/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_3ahasv28u2/clone/recipe/meta.yaml:117: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_3ahasv28u2/clone/recipe/meta.yaml:117: missing_description: The recipe is missing a description
Warnings were found

</details>

2022-12-02 14:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_16akxrd6cz/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_16akxrd6cz/clone/recipe/meta.yaml:118: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_16akxrd6cz/clone/recipe/meta.yaml:118: missing_description: The recipe is missing a description
Warnings were found

</details>

2022-12-02 14:58 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_b92b01hufq/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_b92b01hufq/clone/recipe/meta.yaml:148: missing_description: The recipe is missing a description
WARNING: /tmp/abs_b92b01hufq/clone/recipe/meta.yaml:148: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-02 15:10 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_7e6avjro0y/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_7e6avjro0y/clone/recipe/meta.yaml:120: missing_description: The recipe is missing a description
WARNING: /tmp/abs_7e6avjro0y/clone/recipe/meta.yaml:120: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-02 15:11 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_0acydo2d58/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_0acydo2d58/clone/recipe/meta.yaml:120: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_0acydo2d58/clone/recipe/meta.yaml:120: missing_description: The recipe is missing a description
Warnings were found

</details>

2022-12-05 13:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_d3ajg5mz4o/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_d3ajg5mz4o/clone/recipe/meta.yaml:122: missing_description: The recipe is missing a description
WARNING: /tmp/abs_d3ajg5mz4o/clone/recipe/meta.yaml:122: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-05 13:29 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_54fb8e3ula/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_54fb8e3ula/clone/recipe/meta.yaml:122: missing_description: The recipe is missing a description
WARNING: /tmp/abs_54fb8e3ula/clone/recipe/meta.yaml:122: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-05 14:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_42775n32e4/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_42775n32e4/clone/recipe/meta.yaml:123: missing_description: The recipe is missing a description
WARNING: /tmp/abs_42775n32e4/clone/recipe/meta.yaml:123: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-05 15:34 UTC, cbouss requested changes

2022-12-05 15:34 UTC, cbouss commented on recipe/meta.yaml
>      - libpng
patch and m2-patch can be removed from build

2022-12-05 15:34 UTC, cbouss commented on recipe/meta.yaml
>      - setuptools
I don't see setuptools being required at runtime.

2022-12-05 15:34 UTC, cbouss commented on recipe/meta.yaml
> +{% set tests_to_skip = tests_to_skip + " or test_url_is_accessible" %}  # [osx]
This test is already skipped line 81.

2022-12-05 15:34 UTC, cbouss commented on recipe/meta.yaml
> +    - pytorch
I think we should have a way to specify using pytorch gpu or pytorch cpu based on the build.
Perhaps something like: pytorch 1.*=cpu_*

See https://github.com/pytorch/vision/blob/v0.13.1/packaging/pkg_helpers.bash
https://github.com/pytorch/vision/blob/v0.13.1/packaging/torchvision/meta.yaml

If we are only planning on building the cpu version this time, this can be ignored.

2022-12-05 15:45 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - pytorch
I didn't find requests to build the GPU variant

2022-12-05 15:50 UTC, skupr-anaconda commented on recipe/meta.yaml
> +{% set tests_to_skip = tests_to_skip + " or test_url_is_accessible" %}  # [osx]
Removed it. Thanks!

2022-12-05 15:50 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - setuptools
Removed it. Thanks!

2022-12-05 15:50 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - libpng
Removed them. Thanks!

2022-12-05 15:50 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_4f40scx0fu/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_4f40scx0fu/clone/recipe/meta.yaml:118: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_4f40scx0fu/clone/recipe/meta.yaml:118: missing_description: The recipe is missing a description
Warnings were found

</details>

2022-12-05 16:30 UTC, cbouss commented on recipe/meta.yaml
> +    - pytorch
That's fine then, thank you!

2022-12-05 16:32 UTC, cbouss approved these changes

2022-12-05 17:08 UTC, varlackc approved these changes
LGTM

2022-12-06 07:58 UTC, merged

2022-12-06 07:59 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_d8tr1634j4/clone/recipe/meta.yaml:0: uses_setuptools: The recipe uses setuptools in run depends
WARNING: /tmp/abs_d8tr1634j4/clone/recipe/meta.yaml:118: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_d8tr1634j4/clone/recipe/meta.yaml:118: missing_description: The recipe is missing a description
Warnings were found

</details>